### ISSUE TITLE
string operators not valid in some codepages

### ISSUE THREAD

**Issue by davidedodste** [richardschoen/QshOni#10]
Hello,
as IBM says here https://www.ibm.com/docs/en/i/7.3?topic=commands-operators-in-expressions

> In some national character sets and in the multinational character set, the character | (hexadecimal 4F) is replaced by the character ! (exclamation point). Either ! or *OR can be used as the OR operator and either || or *CAT, !> or *BCAT, and !< or *TCAT can be used for concatenation in those character sets.

I have Italian language, so compiling fails,
Then I issue this command in /tmp/QshOni directory before run build.sh

> `sed -i 's/|/!/g' *`

and programs have been compiled correctly.

**Comment by jwoehr** [comment]
I wonder if the ILE trigraph sequences work for CL etc.
https://www.ibm.com/docs/en/i/7.4?topic=set-trigraph-sequences

On Wed, Apr 13, 2022 at 8:30 AM davidedodste ***@***.***>
wrote:

> I have Italian language, so compiling fails,
>
-- 
Jack Woehr, IBM Champion 2021-2022
<https://www.youracclaim.com/badges/528d23d6-087f-4698-8d17-d59688106ac4/public_url>
Absolute Performance, Inc.
12303 Airport Way, Suite 100
Broomfield, CO 80021

NON-DISCLOSURE NOTICE:  This communication including any and all
attachments is for the intended recipient(s) only and may contain
confidential and privileged information.  If you are not the intended
recipient of this communication, any disclosure, copying further
distribution or use of this communication is prohibited.  If you received
this communication in error, please contact the sender and delete/destroy
all copies of this communication immediately.

**Comment by richardschoen** [comment]
I'm wondering if maybe the CRTSRCPF or CPYFRMSTMF commands in build.sh need to be tweaked when multi-language to set the correct CCSID.  On my machine here in the US it defaults to 37.  You can check your with this: DSPFD FILE(QSHONI/SOURCE) 

Or is the data in the source files in Github off  ?

**Comment by richardschoen** [comment]
Did you run the build from a green screen or SSH session ?

Also, if you're interested in trying this, I updated ***build.sh*** to have a CCSID value. Try changing it and re-building the QSHONI from scratch to see if that works. If the original source file is 280, the data should map appropriately with CPYFROMSTMF I think.
https://github.com/richardschoen/QshOni/blob/master/build.sh

**Comment by richardschoen** [comment]
Also, I can certainly provide a precompiled binary, but I think you would have to change your job to CCSID 37 each time before using and that's not fun.

**Comment by richardschoen** [comment]
Nice. Glad that works. 

It would still be interesting if the build still worked if you changed the CCSID to 280 in build.sh. Theoretically that would handle the PC to CCSID 280 formatting issues.

**Comment by karl-fritz** [comment]
Pls change the shortcuts to regular CAT expressions. Had the same problems as Davide (CCSID 500).

**Comment by richardschoen** [comment]
Did you try changing the srcccsid value in build.sh ?

You can try with either 500 or 37. 

Or how did you initially download and build ?

**Comment by karl-fritz** [comment]
Richard,
I'm a newie with Python.

I used the savf file and tried to compile it. All went ok, except the CLs with the shortstrings to concatinate the strings. I know it's cool to use it, but sometimes ...
Got with the famous old SEU a lot of green reversed lines (unknown character). :-D
(Sorry, I'm using SEU for Q&D edits - till the RDi is started and the right sources selected, the half work is done). 

Further, I assume you know the latest SQL functions how to work with the IFS. Maybe it's not a bad idea to modernize your solution with the newest features for users like me, who work with the latest technologies, like V74/V75 and power 9.
But, I can do it myself too ... (knowing, that's a bunch of users running older systems)

Thanks and cheers,
Karl

**Comment by richardschoen** [comment]
Yeah, for the savf version to recompile you would need to:  CHGJOB CCSID(37)

Using the build.sh script from Github is really the way to go once you get familiar with using git and SSH terminals and you can set your own ccsid in the build.sh script file.  Take a look at that when get feel brave.

I don't plan to use SQL functions to modify IFS files.  Git seems to handle most of that just fine. Thanks for the idea though.
