### ISSUE TITLE
Add QSHPYRUN option Activate Virtual Environment

### ISSUE THREAD

**Issue by jwoehr** [richardschoen/QshOni#13]
Python supports virtual environments which allow isolation of modules from the user's personal Python site package environment and from the global Python site package environment.

The virtual environment is created by the user, e.g., `python -m venv /path/to/my/venv --system-site-packages`

The user then activates the virtual environment and installs therein the desired optional modules via `pip`. The environment is a directory hierarchy which persists and can be deactivated and reactivated at any time.

The environment is activated by sourcing the environment's `activate` script, e.g, `. /path/to/my/venv/bin/activate` (using the dot operator `.` shorthand for the shell `source` command) or more formally `source /path/to/my/venv/bin/activate`

Thereafter, the `deactivate` command (no path necessary to invoke) is present in the environment which will undo the work of the `activate` script. The activation, in any case, expires with the shell that called `activate`.

__This issue__ is to request that an argument be added to `QSHPYRUN` representing the path to the venv which would then cause the execution to activate the indicated virtual environment prior to invoking the indicated Python script.

**Comment by richardschoen** [comment]
How do I check for an activated environment ?  The bash command prompt doesn't change when I test from an SSH terminal session.

**Comment by richardschoen** [comment]
OK, @jwoehr got it to work with this command: ```source /venv1/bin/activate```

I'm trying to visualize the best way to implement this via parms on the QSHPYRUN command 

Something like these parms:
```USEVENV - Use virtual environment```  - Dft - *NO   Options(*NO/*YES)
```VENVPATH - Virtual environment base path``  (Enter base virtual environment path)
activate would be assumed to be in the/bin underneath the venv path. 

How it might work when called via command line:
```source /venv/path/bin/activate;python3 scriptname.py "parm1" "Parn2" "etc";deactivate;```

Q: Is this what you would visualize or could deactivate be left out since the shell ends after processing?

**Comment by richardschoen** [comment]
Initial updates on QSHPYRUN are available. Part of 1.0.17.

**Comment by jwoehr** [comment]
Hi @richardschoen ... apologies for slow response, traveling.

Yes, you are correct, just the base environment path, e.g. `venv/path` ,  since the invocation to activate the venv is always `/venv/path/bin/activate`

Sounds great, I'll try it out soon.

**Comment by jwoehr** [comment]
PS They have this running in production these days! Thanks, @richardschoen
