### ISSUE TITLE
WIBNI the caller could control the target OFS file for command output

### ISSUE THREAD

**Issue by jwoehr** [richardschoen/QshOni#15]
User asked me yesterday if there is a way to control the output destination of the file currently created in QTEMP containing the output from QSH command execution? That lets the caller leave the file around for debugging.

**Comment by richardschoen** [comment]
Currently if they want to aggregate logs they can use the IFSDSTDOUT parm to output and append to an IFS log file to keep the log contents.  And if they need it in a PF they can do a CPYF.  PRTSTDOUT is also useful to log to a spool file.

**Comment by richardschoen** [comment]
Was a little easier to change than I anticipated. You need to build V1.0.16 from source and there is a new outfile parameter that defaults to QTEMP/STDOUTQSH.

**Comment by richardschoen** [comment]
Cosing as done with V1.0.16
