### ISSUE TITLE
Missing closing quote for the IFSFILE on examples on README.MD

### ISSUE THREAD

**Issue by devinhh** [richardschoen/QshOni#16]
Very minor issue.  The closing quote is missing from the IFSFILE on the README.MD page.
Example:
     QSHEXEC CMDLINE('cd /tmp;ls')   
     DSPSTDOUT(*YES)         
     LOGSTDOUT(*NO)          
     PRTSTDOUT(*NO)          
     DLTSTDOUT(*YES)
     IFSSTDOUT(*NO)
     **IFSFILE('/tmp/log.txt)**
     IFSOPT(*REPLACE)
     PRTSPLF(QSHEXECLOG) 
     PRTUSRDTA(*NONE)    
     PRTTXT(*NONE)

**Comment by devinhh** [comment]
There are multiple lines on this page missing the close quote.

**Comment by richardschoen** [comment]
Think I got them all.

**Comment by devinhh** [comment]
One more. Thanks

     QSHBASH CMDLINE('cd /tmp;ls')   
     DSPSTDOUT(*YES)         
     LOGSTDOUT(*NO)          
     PRTSTDOUT(*NO)          
     DLTSTDOUT(*YES)
     IFSSTDOUT(*NO)
     IFSFILE('/tmp/log.txt)
     IFSOPT(*REPLACE)
     PRTSPLF(QSHEXECLOG) 
     PRTUSRDTA(*NONE)    
     PRTTXT(*NONE)

**Comment by richardschoen** [comment]
Think I got it. Thanks.
