### ISSUE TITLE
Constantly getting error: unrecognized arguments: when calling Python script

### ISSUE THREAD

**Issue by josys36** [richardschoen/QshOni#20]
I'm trying to call a send_email python script that takes a few arguments. No matter what your command to run Python scrips keeps telling me error: unrecognized arguments: 

I have tried to pass these arguments 8 ways to Sunday and no success. 

Here is an example of one of the arguments. 

--host smtp.office365.com

I can run my script passing all the arguments from a shell session without any problem. So how do I pass them using your command?

Jason

**Comment by josys36** [comment]
How do you pass simple arguments like --host smtp.office365.com from your command? 

Here is the definition in the Python program,

parser.add_argument("--host", help="SMTP Server.")

How do I pass that using your command?

**Comment by richardschoen** [comment]
QSHONI/QSHEXEC CMDLINE('python3 --host smtp.office365.com')

**Comment by josys36** [comment]
I'm not using QSHEXEC I'm using QSHPYRUN. Which one should I be using?

**Comment by richardschoen** [comment]
Either will work. Pick your poison. 

QSHONI/QSHPYRUN SCRIPTDIR('/python') SCRIPTFILE(pysample1.py) ARGS('--host' 'smtp.office365.com ')              
                DSPSTDOUT(*YES)                              

In the Python variant each command line element is a parm.

**Comment by josys36** [comment]
I think you have a problem when the argument is a string with spaces. For instance if you pass an email subject or email message. Those are going to have spaces and need double quotes. I'm going to do some testing and report back.

**Comment by richardschoen** [comment]
Each parm in ARGS automatically gets double-quotes placed around it so there should not be an issue with blank parms. Just pass a blank value with single quotes  ```' '```. Let me know how it goes.

**Comment by richardschoen** [comment]
Double quotes are natural parm delimiters in PASE. They get ignored by the scripts when added.

**Comment by josys36** [comment]
CMD ....+....1....+....2....+....3....+....4....+....5....+....6....+....7....+
     ************Beginning of data**************                               
    usage: send_email.py [-h] [--host HOST] [--port PORT] [--user USER]        
                         [--password PASSWORD] [--from_address FROM_ADDRESS]   
                         [--to_addresses [TO_ADDRESSES ...]] [--subject SUBJECT
                         [--message MESSAGE] [--attachments [ATTACHMENTS ...]] 
    send_email.py: error: unrecognized arguments: --host smtp.office365.com    

I passed one argument into the Python script (--host) and this is what I'm getting.

**Comment by richardschoen** [comment]
Not sure. Upload a simple script sample and I can look at it sometime later.   

I don't find any flaws in the QSHPYRUN command though.    

Honestly you are probably better off using QSHEXEC since you control the entire command line.

**Comment by richardschoen** [comment]
Oh, and did you also pass your smtp.office365.com argument as parm 2 ?

I'm making an assumption since you're still not showing me specifics.

**Comment by josys36** [comment]
No that's parm one.

**Comment by richardschoen** [comment]
I have nothing further to add unless you post a sample.

**Comment by josys36** [comment]
I'll make one, I'm currently in meetings so will be late today or early tomorrow.

**Comment by josys36** [comment]
Here is a Python script that takes in one argument that should print to the console.

`import argparse

def process_arguments():

    parser = argparse.ArgumentParser()

    parser.add_argument("--output", required=True, help="Show Output")

    args = parser.parse_args()

    if args.output:
        print(f"Displaying Output as: {args.output}")


if __name__ == "__main__":
    process_arguments()
`

When I run this on Windows or Linux I can pass a command line argument like this,

--output "This is a test."

The console shows the result. 

Anytime I run this using QSHPYRUN, I get 

usage: passing_arguments.py [-h] --output OUTPUT                           
passing_arguments.py: error: the following arguments are required: --output

QSHPYRUN SCRIPTDIR('/home/jasono/Python/Testing') SCRIPTFILE(passing_argu
ments.py) ARGS('--output Hello World') DSPSTDOUT(*YES) LOGSTDOUT(*YES)   
Python script /home/jasono/Python/Testing/passing_arguments.py failed.   
  See the joblog or stdout log.

**Comment by richardschoen** [comment]
Right. You didn't follow my instructions above: "In the Python variant each command line element is a parm." 

This works as expected  based on my example above:

```
 QSHONI/QSHPYRUN SCRIPTDIR('/python')    
                 SCRIPTFILE(qshpyruntest1.py)                 
                 ARGS('--output' 'This is a test')            
                 DSPSTDOUT(*YES)                              
```

Produces: ```Displaying Output as: This is a test ```                  
                 
If you insure each command line element is passed as a separate argument you're good to go.

**Comment by richardschoen** [comment]
If you use QSHEXEC, thius produces the same output:

```
QSHONI/QSHEXEC CMDLINE('python3 /qshpyruntest1.py "--output" "This is a test"')                              
               DSPSTDOUT(*YES)                                 
```

As does this:

```
QSHONI/QSHEXEC CMDLINE('python3 /qshpyruntest1.py --output "This is a test"')                              
               DSPSTDOUT(*YES)                                 
```

This does not work because parm 2 is not surrounded by double quotes to denote it's an entire parm value:
```
QSHONI/QSHEXEC CMDLINE('python3 /qshpyruntest1.py --output This is a test')                              
               DSPSTDOUT(*YES)                                 
```
