### ISSUE TITLE
Lines not splitting when a carraige return is encounterd by itself.

### ISSUE THREAD

**Issue by IJOY94** [richardschoen/QshOni#23]
I'm having an issue where my call to QSHEXEC works correctly, but the standard out that is written to QTEMP/STDOUTQSH does not split when it encounters a carriage return, causing a lot of difficulty as I try to process this output. I'm not seeing any LFs following the CRs, much to my bewilderment.

**Comment by IJOY94** [comment]
`  █cd `/DATA/TEST/INCOMING' [Connecting...]█cd `/DATA/TEST/INCOMING' [Connected]      █                                      █cd ok, cwd=/DATA/TEST/INCOMING
lcd ok, local cwd=/tstservers/FTP/DATA/TEST/INCOMING                                                                 
--------------------                                                                                                 
`rels' at 0 [Waiting for response...]█`rels' at 0 [Receiving data]           █                              █drwxrwx-wx   1 user     group           0 Apr 13 18:00 ARCHIVE
--------------------                                                                                                 
                                                                                                                     `

**Comment by richardschoen** [comment]
Please post a specific recreatable sample scenario with actual code to run and I can test.

**Comment by IJOY94** [comment]
```
             QSHEXEC    CMDLINE('echo "With CRs:";+
                                 printf "Hello,\r+
                                         how\r+
                                         are\r+
                                         you\r+
                                         today?\r";+
                                 echo; +
                                 echo "With LFs:";+
                                 printf "Hello,\n+
                                         how\n+
                                         are\n+
                                         you\n+
                                         today?\n"')
```

Should result in:

```
With CRs:                 
Hello,█how█are█you█today?█
With LFs:                 
Hello,                    
how                       
are                       
you                       
today?                    
```

**Comment by richardschoen** [comment]
Interestingly if you put the following in a file and name it: ```printf1.sh``` and run the script from from ```STRQSH``` or via SSH with ```qsh printf1.sh```

```
 echo "With CRs:"
 printf "Hello,\rhow\rare\ryou\rtoday?\r"
 echo 
 echo "With LFs:"
 printf "Hello,\nhow\nare\nyou\ntoday?\n"
 echo "With CRLFs:"
 printf "Hello,\r\nhow\r\nare\r\nyou\r\ntoday?\r\n"                      
```

The only part of the ```With CRs``` line that shows is ```today?```, so you actually lose data when you run the same script directly from STRQSH or as a script - printf1.sh.

STRQSH and SSH output results of printf1.sh

```
With CRs:
today?         <----Notice the lost data 
With LFs:
Hello,
how
are
you
today?
With CRLFs:
Hello,
how
are
you
today?
```

So running in STRQSH and via qsh command line in SSH actually loses data in the first section. 

So which is the real expected result ??  That is the question.

**Comment by richardschoen** [comment]
One thought I had was that you will normally either see ```\n```  - NewLine or ```\r\n``` - CRLF and not a ```\r``` - CR in scripting.  Perhaps the ```QIBM_QSH_CMD_OUTPUT``` environment variable which we use to output the STDOUT logging to the IFS is nice enough to sort of handle the \r by itself when found.

**Comment by richardschoen** [comment]
One final thought is to probably not mix printf and echo in a script. 

I don’t think your sample would be used in a real production scenario. If it is, don’t use bare carriage returns \r. Use new line instead.

I’m going to close this as I don’t believe it’s an issue with QSHEXEC.
