### ISSUE TITLE
I execute the following CALL PGM(QSHONI/SRCBLDC) but it stopped 

### ISSUE THREAD

**Issue by kgiampa** [richardschoen/QshOni#25]
CALL PGM(QSHONI/SRCBLDC)                                                   
La libreria QSHONI gi{ esiste nell'elenco delle librerie.                  
Comando QSHPATH creato nella libreria QSHONI.                              
Non } stata trovata l'unit{ di stampa PRT01. La coda di emissione } stata  
  modificata con QPRINT nella libreria QGPL.                               
Programma QSHPATHC creato nella libreria QSHONI.                           
                                                                  Segue... 
Comando QSHEXEC creato nella libreria QSHONI.                             
Non } stata trovata l'unit{ di stampa PRT01. La coda di emissione } stata 
  modificata con QPRINT nella libreria QGPL.                              
Programma QSHEXECC creato nella libreria QSHONI.                          
Non } stata trovata l'unit{ di stampa PRT01. La coda di emissione } stata 
  modificata con QPRINT nella libreria QGPL.                              
**Il file QRPGLESRC nella libreria QSYSINC con il membro QUSEC non } stato  
  trovato.**                                                                
Il file QRPGLESRC nella libreria QSYSINC con il membro QUSEC non } stato  
  trovato.                                                                
**La compilazione si } arrestata. Nel programma sono stati trovati errori di
  gravit{ 40.**                   

Versione operating system
5770SS1            *COMPATIBLE  V7R4M0 L00        
5770SS1            *COMPATIBLE  V7R4M0 L00        
5770SS1    1       *COMPATIBLE  V7R4M0            
5770SS1    2       *COMPATIBLE  V7R4M0            
5770SS1    3       *COMPATIBLE  V7R4M0            
5770SS1    5                                      
5770SS1    6                                      
5770SS1    7                                      
5770SS1    8       *COMPATIBLE  V7R4M0            
5770SS1    9                                      
5770SS1    12      *COMPATIBLE  V7R4M0            
5770SS1    13

**Comment by richardschoen** [comment]
It appears you are missing the following possibly:
```5770SS1   *COMPATIBLE  System Openness Includes  ```
