### ISSUE TITLE
Issue when install with build.sh

### ISSUE THREAD

**Issue by GautierFR** [richardschoen/QshOni#27]
I don't know why, but I meet an issue during SRCBLDC compilation process. And if I change  "|>" operator by *BCAT,  compilation is ok for this *PGM. 

But calling this program doesn't seem to compile the other objects and LIB QSHONI have only : 
- SRCBLDC *PGM
- SOURCE srcpf
- QSHPATH *CMD

**Comment by richardschoen** [comment]
In build.sh there is a SRCCCSID parameter.  Default=37. Change it to your desired source CCSID value and run again. 

Otherwise from a 5250 job you can do CHGJOB CCSID(37) and it should build just fine by manually compiling SRCBLDC and running it.

**Comment by GautierFR** [comment]
I already follow this step (https://github.com/richardschoen/QshOni?tab=readme-ov-file#installing-and-building-qshoni-via-git-clone-and-buildsh) and I not forget to change SRCCCSID in build.sh with my value : 297. I will test manually.

**Comment by richardschoen** [comment]
Cool. glad that helped. 

I'll talk to the quality control person on testing the build process :-)
