### ISSUE TITLE
"missing" AQCPFMSG message file

### ISSUE THREAD

**Issue by bdietz400** [richardschoen/QshOni#28]
in QSHIFSSIZC.CLLE  missing that message file. assuming you meant just QCPFMSG

I also think you may want to change the 'stat' to 'stat64' to handle large size IFS objects

**Comment by richardschoen** [comment]
Updated that message reference.  

If I switch to stat64 do you know the max size that can get returned ?   

Also does the binary need to get switched from 4-8 bytes ?  I inherited this example originally.

**Comment by bdietz400** [comment]
I think this may help.
https://www.ibm.com/support/pages/control-language-cl-programming-declaring-integer-data-type
4-byte signed integer values could range from -2147483648 to 2147483647
4-byte unsigned integers from 0 to 4294967295
 8-byte signed integers can store a value ranging from -9223372036854775808 to 9223372036854775807
 8-byte unsigned integers a range from 0 to 18446744073709551615

**Comment by richardschoen** [comment]
Looks like stat64 and 8byte binary value can't be easily returned unless I convert the command processing program to use an 8 character binary value.  This most likely means bringing RPG into the mix to call stat64 since it handles integer fields. 
However the CL command return values would still be limited to 15 digits since that's the max that a CL command can return. That could mean re-tooling the command to return data areas to QTEMP or an environment variable instead of directly.   

That's more work than I want to put into this particular command at the moment, but I will tweak it to at least return up to 10 places for the binary 4.  

Most files this would be intended to be used with should bless than 2GB I would imagine. I
ll leave this open for future work.

**Comment by bdietz400** [comment]
I found this example from Bob Cozzi.  I think it was from a magazine/book article(i cannot find)

      /IF DEFINED(*CRTRPGMOD)
     H NOMAIN
      /ELSE
     H DFTACTGRP(*NO)
      /ENDIF
     H OPTION(*NODEBUGIO:*SRCSTMT) BNDDIR('QC2LE')
     H*Copyright('(c) 2006 Robert Cozzi, Jr. All rights reserved.')
     H*************************************************************
         /////////////////////////////////////////////////////////
         //  Extension library for RPG IV.
         //  From Bob Cozzi's "RPG TNT - 101 Tips & Tech"
         //  (c) 2006 by Robert Cozzi, Jr. All rights reserved.
         //  ----------------------------------------------------
         //  Permission to use for any programming purpose such as
         //  commercial, free, open-source is hereby granted.
         //  Permission is denied to republish this source except
         //  as indicated above.
         /////////////////////////////////////////////////////////
     H*************************************************************
          //  Move this prototype to a separate source member
          //  then /COPY it in where needed.
          //  Could also merge this entire source member with
          //  tools library (like the one in RPGTNT).
      *************************************************************
      *** BEGIN CUT ***********************************************
     D RtvIFSSize      PR            20I 0
     D   szFile                     640A   Const Varying
      *************************************************************
      *** END CUT *************************************************
     D ifsStat         PR            10I 0 extProc('stat64')
     D  ifsFile                        *   Value options(*string)
     D  pStat                          *   Value

      /IF DEFINED(*V6R1M0)
     D ifsStat_T       DS                  TEMPLATE
      /ELSE
     D ifsStat_T       DS                  Qualified based(ptr_Nothing)
      /ENDIF
     D  fileMode                     10U 0
     D  srlNbr                       10U 0
     D  userID                       10U 0
     D  groupID                      10U 0
     D  nFileSize                    20I 0
     D  lastFileAccess...
     D                               10I 0
     D  lastModTime                  10I 0
     D  lastStsChgTime...
     D                               10I 0
     D  devID                        10U 0
     D  blockSize                    10U 0
     D  symbLinkCount                 5U 0
     D  codePage                      5U 0
     D  allocSize                    20U 0
     D  genID                        10U 0
     D  objectType                   11A
     D  reserved2                     5A
     D  rdev                         10U 0
     D  rdev64                       20U 0
     D  dev64                        20U 0
     D  nlink32                      10U 0
     D  vfs                          10U 0
     D  reserved1                    22A
     D  ccsid                         5U 0
      /IF DEFINED(*CRTBNDRPG)
     D ifsSize         S             10u 0
     D ifsName         S            640A
     D inFile          S            640A
     D rtnSize         S             10P 0
     C                   EVAL      *INLR = *ON
     C     *ENTRY        PLIST
     C                   PARM                    inFile
     C                   PARM                    rtnSize
      /free
           if (%parms() >= 1);
              ifsName = %trimR(inFile);
           else;  // If no name provided,
                  //  use the stat.h file just for fun.
              ifsName = '/usr/include/sys/stat.h';
           endif;
           ifsSize = rtvIFSSize(%TrimR(ifsName));
           if (%parms() >= 2);
              rtnSize = ifsSize;
           endif;
           snd-msg %trimr(ifsName);
           snd-msg %char(ifssize);
           return;
      /end-free

      /ENDIF

      ************************************************************
      **  RtvIFSSize - Get the size of a file on the IFS.       **
      ************************************************************
     P RtvIFSSize      B
      /IF DEFINED(*CRTRPGMOD)
     P                                     EXPORT
      /ENDIF
     D RtvIFSSize      PI            20I 0
     D   szFile                     640A   Const Varying

     D myStatus        DS                  LikeDS(ifsStat_T)
          //  Check to see if the file exists.
     C                   if        ifsStat(%trimR(szFile) :
     C                                     %addr(myStatus) ) < 0

          //  If file not found or not authorized, return -1.
          //  Caller could check errno() to determine the exact error.
     C                   return    -1
     C                   endif

          // return file size in bytes.
     C                   return    myStatus.nFileSize
     P RtvIFSSize      E

**Comment by bdietz400** [comment]
i did find a cl example that uses stat64
https://blog.faq400.com/en/system-administration-en/export-source-code-to-ifs/

**Comment by richardschoen** [comment]
OK I was able to extract what I needed from that link. Nice find. You can rebuild the entire library as V1.0.33 or just download and compile: QSHIFSSIZC and it should now return up to a 15,0 object size from the CL command. I think that's the max size a CL command can return.

**Comment by richardschoen** [comment]
I'm closing this as completed.  Give it a try when you get a chance.

**Comment by richardschoen** [comment]
Completed change.
