### ISSUE TITLE
Error on compile  CL programs

### ISSUE THREAD

**Issue by python64** [richardschoen/QshOni#3]
Hi, 
I downloaded your script via Git clone and build.sh
I have a compile error after run build.sh  

***************************************
   8500-  /* Create and set data area for version                      */
 5770SS1 V7R3M0  160422                  Lingua controllo         QSHONI/SRCBLDC        S0645B1R 14/06/21 12:31:07         Pag.    3
                                      Origine linguaggio di controllo
 NUMSEQ  *...+... 1 ...+... 2 ...+... 3 ...+... 4 ...+... 5 ...+... 6 ...+... 7 ...+... 8 ...+... 9 ...+.  DATA
   8600-              CRTDTAARA  DTAARA(&DESTLIB/VERSION) TYPE(*CHAR) LEN(30) +
   8700                            VALUE(&VERSION) TEXT(&DESTLIB |> 'version')
* CPD0018 30  La stringa '|> 'VERSIO' contiene un carattere non valido.
_(translate error in english) _*  the string '|> &VERSIO'  contains invalid charater ._
   8800-              MONMSG     MSGID(CPF0000)
   8900-              CHGDTAARA  DTAARA(&DESTLIB/VERSION *ALL) VALUE(&VERSION)
   9000-
   9100-  /* Create and set data area for Python binary location - 1.05 */
   9200-              CRTDTAARA  DTAARA(QSHONI/PYPATH) TYPE(*CHAR) LEN(255) +
   9300                            VALUE('/QOpenSys/pkgs/bin') TEXT('Path to +
   9400                            Python Binaries')
   9500-
   9600-  /* Change library desc to match the version */
   9700-              CHGLIB     LIB(QSHONI) TEXT('QShell on IBM i -' |> +
   9800                            &VERSION)
*** CPD0018 30  La stringa '|> &VERSIO' contiene un carattere non valido.
_(translate error in english) _*  the string '|> &VERSIO'  contains invalid charater ._
   9900-
***************************************

I try to search a workaround to this srcipt, but the problem is pervasive...  
QSHBASHC   line 0047 
QSHIFSCHKC  line  38, 45, 55, 
QSHPATHC   line 29 
QSHPYRUNC   a lot of statements

My Iseries s.o. is  7.3.  

How i can solve the compilation problem?

Regards
Alessandro

**Comment by richardschoen** [comment]
I'm guessing perhaps your machine is not running CCSID 37 as primary ?  On the CRTPF for SOURCE and CPYFRMSTMF you may have to make sure you specify the right CCSID so the PC files convert correctly.  

For any tweaks you can manually edit the source files once they are copied into QSHONI/SOURCE also and compile directly from the library.

**Comment by python64** [comment]
Hi Richard,
thanks for your reply,  
I follow. .savf way...   now the compile is OK! 

I don't find savf of V1.0.6, so I downloaded V1.0.5. 

fine work :)
Alessandro

**Comment by richardschoen** [comment]
I also added the V1.0.6 save file as well now under releases.

**Comment by python64** [comment]
Thanks a lot !  :)
