### ISSUE TITLE
newline error running getrepo-qshoni.sh

### ISSUE THREAD

**Issue by alanseiden** [richardschoen/QshOni#30]
I downloaded the file like this:
`wget -P /tmp/ https://github.com/richardschoen/QshOni/blob/master/getrepo-qshoni.sh
`
Then ran it:
`bash /tmp/getrepo-qshoni.sh`

Errors:
- /tmp/getrepo-qshoni.sh: line 7: `syntax error near unexpected token newline'
- /tmp/getrepo-qshoni.sh: line 7: `<!DOCTYPE html>`

**Comment by richardschoen** [comment]
Interesting. It seems that wget perhaps injected something into the file ?  They file itself has no html tags in it.

**Comment by richardschoen** [comment]
You probably need this URL:   
https://raw.githubusercontent.com/richardschoen/QshOni/refs/heads/master/getrepo-qshoni.sh   

The one you were using definitely returned an HTML stream.

**Comment by alanseiden** [comment]
Thanks!

**Comment by richardschoen** [comment]
His one is even better since you don't need to use the raw. address
https://github.com/richardschoen/QshOni/raw/refs/heads/master/getrepo-qshoni.sh
