### ISSUE TITLE
Command QSHEXEC > Copy std output to IFS file  (CPYTOSTMF) command

### ISSUE THREAD

**Issue by dennisnel** [richardschoen/QshOni#7]
https://github.com/richardschoen/QshOni/blob/47a2cfca2fd88c873abe820a5004a20a0dfed03c/QSHEXECC.CLLE#L297

The default value for the AUT parameter of the CPYTOSTMF command is *DFT which translates to the primary group and *PUBLIC having *NONE data authority.

We copy the logs to the IFS in order for our RTB team to investigate when required. At the current setting they don't have authority to the log file.

Could the value for the AUT parameter be changed to *INDDIR? or an additional parameter AUT be added to the QSHEXEC command which could then be used in the CPYTOSTMF command?

**Comment by richardschoen** [comment]
For now it probably makes sense to use *INDIR since most permissions are set at the dir level already. Might add as an external parm later if it makes sense to do so. Download and build again and you should have the right stuff in QSHEXECC now.

**Comment by dennisnel** [comment]
Thanks @richardschoen, I'll download the latest release and give it a spin.
